# Generated by Django 2.0.7 on 2019-03-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='lname',
        ),
        migrations.AlterField(
            model_name='content',
            name='fname',
            field=models.CharField(max_length=100),
        ),
    ]
