# Generated by Django 2.0.7 on 2019-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190324_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='about2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
